### ISSUE TITLE
How to start the shell? 

### ISSUE THREAD

**Issue by scottwhudson** [supasate/yosh#1]
Total python noob here, how does one start the shell during the tutorial?  Is it just `python shell.py`?

**Comment by supasate** [comment]
@scottwhudson In the beginning of the tutorial when you deal with only `shell.py`, you can just start it with `python shell.py`. However, later in the tutorial, there are several modules contained in namespaces. So, you have to type `python -m yosh.shell` outside yosh folder instead.
