### ISSUE TITLE
`echo` does not work

### ISSUE THREAD

**Issue by supasate** [supasate/yosh#5]

**Comment by TeddyNight** [comment]
It works.I tested it on my computer.

**Comment by TeddyNight** [comment]
What's the matter with 'echo'?

**Comment by supasate** [comment]
It seems like the output of echo is not shown on my machine (OS X). I'll check it out.

**Comment by TeddyNight** [comment]
That's strange.

**Comment by TeddyNight** [comment]
I just test it on the Windows and Linux (Archlinux and Centos).

**Comment by supasate** [comment]
Seems strange that it works on your machine. 

I found that the root cause is that `subprocess.Popen` takes only command name without arguments which starts from [this commit](https://github.com/supasate/yosh/pull/3/commits/1385dd13481a5f97d4a2679cbb53f83535e4f4d8#diff-a7d9e02417dce0de832d21f61cf3d9e9R43).

I already fixed in the master branch.
